# -*- coding: utf-8 -*-
"""Generate the winhttp.dll proxy scaffolding (winhttp.def / winhttp_orig.def /
thunks.asm / names.txt) from the real system winhttp.dll's export table.

Replaces FiberShop's gen_proxy.bat (which needed dumpbin + vcvars); this parses
the PE directly so it can run anywhere python is.
"""
import os
import struct
import sys

REAL = r'C:\Windows\System32\winhttp.dll'
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'native')


def read_exports(path):
    d = open(path, 'rb').read()
    e = struct.unpack_from('<I', d, 0x3c)[0]
    nsec = struct.unpack_from('<H', d, e + 6)[0]
    optsz = struct.unpack_from('<H', d, e + 20)[0]
    opt = e + 24
    magic = struct.unpack_from('<H', d, opt)[0]
    ddir = opt + (112 if magic == 0x20b else 96)
    erva, esz = struct.unpack_from('<II', d, ddir)
    secs = []
    so = opt + optsz
    for i in range(nsec):
        s = so + 40 * i
        vsz, va, rsz, ra = struct.unpack_from('<IIII', d, s + 8)
        secs.append((va, vsz, ra, rsz))

    def r2o(rva):
        for va, vsz, ra, rsz in secs:
            if va <= rva < va + max(vsz, rsz):
                return ra + (rva - va)
        raise ValueError('bad rva %#x' % rva)

    o = r2o(erva)
    nfun, nnam = struct.unpack_from('<II', d, o + 0x14)
    base = struct.unpack_from('<I', d, o + 0x10)[0]
    npt_rva, ot_rva = struct.unpack_from('<II', d, o + 0x20)
    npt, ot = r2o(npt_rva), r2o(ot_rva)
    named = {}
    for i in range(nnam):
        nr = struct.unpack_from('<I', d, npt + 4 * i)[0]
        no = r2o(nr)
        nm = d[no:d.index(b'\0', no)].decode('latin1')
        named[struct.unpack_from('<H', d, ot + 2 * i)[0]] = nm
    ordinals = sorted(named)
    unnamed = [base + i for i in range(nfun) if i not in named]
    return ordinals, named, unnamed


def main():
    ordinals, named, unnamed = read_exports(REAL)
    names = [named[i] for i in ordinals]
    if unnamed:
        print('[!] %d ordinal-only exports (not forwarded): %s' % (len(unnamed), unnamed))
    print('[i] %d named exports from %s' % (len(names), REAL))

    os.makedirs(OUT, exist_ok=True)

    with open(os.path.join(OUT, 'names.txt'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(names) + '\n')

    with open(os.path.join(OUT, 'winhttp.def'), 'w', encoding='utf-8') as f:
        f.write('LIBRARY winhttp\nEXPORTS\n')
        for n in names:
            f.write('    %s=th_%s\n' % (n, n))

    with open(os.path.join(OUT, 'winhttp_orig.def'), 'w', encoding='utf-8') as f:
        f.write('LIBRARY winhttp_orig\nEXPORTS\n')
        for n in names:
            f.write('    %s\n' % n)

    with open(os.path.join(OUT, 'thunks.asm'), 'w', encoding='utf-8') as f:
        f.write('; auto-generated by tools/gen_proxy.py - do not edit\n')
        f.write('option casemap:none\n\n')
        for n in names:
            f.write('EXTERN __imp_%s:QWORD\n' % n)
        f.write('\n.code\n')
        for n in names:
            f.write('th_%s PROC\n    jmp QWORD PTR [__imp_%s]\nth_%s ENDP\n' % (n, n, n))
        f.write('\nEND\n')

    print('[ok] wrote names.txt / winhttp.def / winhttp_orig.def / thunks.asm -> %s' % os.path.normpath(OUT))


if __name__ == '__main__':
    main()
