; auto-generated by tools/gen_proxy.py - do not edit
option casemap:none

EXTERN __imp_DllCanUnloadNow:QWORD
EXTERN __imp_DllGetClassObject:QWORD
EXTERN __imp_Private1:QWORD
EXTERN __imp_SvchostPushServiceGlobals:QWORD
EXTERN __imp_WinHttpAddRequestHeaders:QWORD
EXTERN __imp_WinHttpAddRequestHeadersEx:QWORD
EXTERN __imp_WinHttpAutoProxySvcMain:QWORD
EXTERN __imp_WinHttpCheckPlatform:QWORD
EXTERN __imp_WinHttpCloseHandle:QWORD
EXTERN __imp_WinHttpConnect:QWORD
EXTERN __imp_WinHttpConnectionDeletePolicyEntries:QWORD
EXTERN __imp_WinHttpConnectionDeleteProxyInfo:QWORD
EXTERN __imp_WinHttpConnectionFreeNameList:QWORD
EXTERN __imp_WinHttpConnectionFreeProxyInfo:QWORD
EXTERN __imp_WinHttpConnectionFreeProxyList:QWORD
EXTERN __imp_WinHttpConnectionGetNameList:QWORD
EXTERN __imp_WinHttpConnectionGetProxyInfo:QWORD
EXTERN __imp_WinHttpConnectionGetProxyList:QWORD
EXTERN __imp_WinHttpConnectionOnlyConvert:QWORD
EXTERN __imp_WinHttpConnectionOnlyReceive:QWORD
EXTERN __imp_WinHttpConnectionOnlySend:QWORD
EXTERN __imp_WinHttpConnectionSetPolicyEntries:QWORD
EXTERN __imp_WinHttpConnectionSetProxyInfo:QWORD
EXTERN __imp_WinHttpConnectionUpdateIfIndexTable:QWORD
EXTERN __imp_WinHttpCrackUrl:QWORD
EXTERN __imp_WinHttpCreateProxyList:QWORD
EXTERN __imp_WinHttpCreateProxyManager:QWORD
EXTERN __imp_WinHttpCreateProxyResolver:QWORD
EXTERN __imp_WinHttpCreateProxyResult:QWORD
EXTERN __imp_WinHttpCreateUiCompatibleProxyString:QWORD
EXTERN __imp_WinHttpCreateUrl:QWORD
EXTERN __imp_WinHttpDetectAutoProxyConfigUrl:QWORD
EXTERN __imp_WinHttpFreeProxyResult:QWORD
EXTERN __imp_WinHttpFreeProxyResultEx:QWORD
EXTERN __imp_WinHttpFreeProxySettings:QWORD
EXTERN __imp_WinHttpFreeProxySettingsEx:QWORD
EXTERN __imp_WinHttpFreeQueryConnectionGroupResult:QWORD
EXTERN __imp_WinHttpGetDefaultProxyConfiguration:QWORD
EXTERN __imp_WinHttpGetIEProxyConfigForCurrentUser:QWORD
EXTERN __imp_WinHttpGetProxyForUrl:QWORD
EXTERN __imp_WinHttpGetProxyForUrlEx:QWORD
EXTERN __imp_WinHttpGetProxyForUrlEx2:QWORD
EXTERN __imp_WinHttpGetProxyForUrlHvsi:QWORD
EXTERN __imp_WinHttpGetProxyResult:QWORD
EXTERN __imp_WinHttpGetProxyResultEx:QWORD
EXTERN __imp_WinHttpGetProxySettingsEx:QWORD
EXTERN __imp_WinHttpGetProxySettingsResultEx:QWORD
EXTERN __imp_WinHttpGetProxySettingsVersion:QWORD
EXTERN __imp_WinHttpGetTunnelSocket:QWORD
EXTERN __imp_WinHttpOpen:QWORD
EXTERN __imp_WinHttpOpenRequest:QWORD
EXTERN __imp_WinHttpPacJsWorkerMain:QWORD
EXTERN __imp_WinHttpProbeConnectivity:QWORD
EXTERN __imp_WinHttpProtocolCompleteUpgrade:QWORD
EXTERN __imp_WinHttpProtocolReceive:QWORD
EXTERN __imp_WinHttpProtocolSend:QWORD
EXTERN __imp_WinHttpQueryAuthSchemes:QWORD
EXTERN __imp_WinHttpQueryConnectionGroup:QWORD
EXTERN __imp_WinHttpQueryDataAvailable:QWORD
EXTERN __imp_WinHttpQueryHeaders:QWORD
EXTERN __imp_WinHttpQueryHeadersEx:QWORD
EXTERN __imp_WinHttpQueryOption:QWORD
EXTERN __imp_WinHttpReadData:QWORD
EXTERN __imp_WinHttpReadDataEx:QWORD
EXTERN __imp_WinHttpReadProxySettings:QWORD
EXTERN __imp_WinHttpReadProxySettingsHvsi:QWORD
EXTERN __imp_WinHttpReceiveResponse:QWORD
EXTERN __imp_WinHttpRefreshProxySettings:QWORD
EXTERN __imp_WinHttpRegisterProxyChangeNotification:QWORD
EXTERN __imp_WinHttpResetAutoProxy:QWORD
EXTERN __imp_WinHttpResolverGetProxyForUrl:QWORD
EXTERN __imp_WinHttpSaveProxyCredentials:QWORD
EXTERN __imp_WinHttpSendRequest:QWORD
EXTERN __imp_WinHttpSetCredentials:QWORD
EXTERN __imp_WinHttpSetDefaultProxyConfiguration:QWORD
EXTERN __imp_WinHttpSetOption:QWORD
EXTERN __imp_WinHttpSetProxySettingsPerUser:QWORD
EXTERN __imp_WinHttpSetSecureLegacyServersAppCompat:QWORD
EXTERN __imp_WinHttpSetStatusCallback:QWORD
EXTERN __imp_WinHttpSetTimeouts:QWORD
EXTERN __imp_WinHttpTimeFromSystemTime:QWORD
EXTERN __imp_WinHttpTimeToSystemTime:QWORD
EXTERN __imp_WinHttpUnregisterProxyChangeNotification:QWORD
EXTERN __imp_WinHttpWebSocketClose:QWORD
EXTERN __imp_WinHttpWebSocketCompleteUpgrade:QWORD
EXTERN __imp_WinHttpWebSocketQueryCloseStatus:QWORD
EXTERN __imp_WinHttpWebSocketReceive:QWORD
EXTERN __imp_WinHttpWebSocketSend:QWORD
EXTERN __imp_WinHttpWebSocketShutdown:QWORD
EXTERN __imp_WinHttpWriteData:QWORD
EXTERN __imp_WinHttpWriteProxySettings:QWORD

.code
th_DllCanUnloadNow PROC
    jmp QWORD PTR [__imp_DllCanUnloadNow]
th_DllCanUnloadNow ENDP
th_DllGetClassObject PROC
    jmp QWORD PTR [__imp_DllGetClassObject]
th_DllGetClassObject ENDP
th_Private1 PROC
    jmp QWORD PTR [__imp_Private1]
th_Private1 ENDP
th_SvchostPushServiceGlobals PROC
    jmp QWORD PTR [__imp_SvchostPushServiceGlobals]
th_SvchostPushServiceGlobals ENDP
th_WinHttpAddRequestHeaders PROC
    jmp QWORD PTR [__imp_WinHttpAddRequestHeaders]
th_WinHttpAddRequestHeaders ENDP
th_WinHttpAddRequestHeadersEx PROC
    jmp QWORD PTR [__imp_WinHttpAddRequestHeadersEx]
th_WinHttpAddRequestHeadersEx ENDP
th_WinHttpAutoProxySvcMain PROC
    jmp QWORD PTR [__imp_WinHttpAutoProxySvcMain]
th_WinHttpAutoProxySvcMain ENDP
th_WinHttpCheckPlatform PROC
    jmp QWORD PTR [__imp_WinHttpCheckPlatform]
th_WinHttpCheckPlatform ENDP
th_WinHttpCloseHandle PROC
    jmp QWORD PTR [__imp_WinHttpCloseHandle]
th_WinHttpCloseHandle ENDP
th_WinHttpConnect PROC
    jmp QWORD PTR [__imp_WinHttpConnect]
th_WinHttpConnect ENDP
th_WinHttpConnectionDeletePolicyEntries PROC
    jmp QWORD PTR [__imp_WinHttpConnectionDeletePolicyEntries]
th_WinHttpConnectionDeletePolicyEntries ENDP
th_WinHttpConnectionDeleteProxyInfo PROC
    jmp QWORD PTR [__imp_WinHttpConnectionDeleteProxyInfo]
th_WinHttpConnectionDeleteProxyInfo ENDP
th_WinHttpConnectionFreeNameList PROC
    jmp QWORD PTR [__imp_WinHttpConnectionFreeNameList]
th_WinHttpConnectionFreeNameList ENDP
th_WinHttpConnectionFreeProxyInfo PROC
    jmp QWORD PTR [__imp_WinHttpConnectionFreeProxyInfo]
th_WinHttpConnectionFreeProxyInfo ENDP
th_WinHttpConnectionFreeProxyList PROC
    jmp QWORD PTR [__imp_WinHttpConnectionFreeProxyList]
th_WinHttpConnectionFreeProxyList ENDP
th_WinHttpConnectionGetNameList PROC
    jmp QWORD PTR [__imp_WinHttpConnectionGetNameList]
th_WinHttpConnectionGetNameList ENDP
th_WinHttpConnectionGetProxyInfo PROC
    jmp QWORD PTR [__imp_WinHttpConnectionGetProxyInfo]
th_WinHttpConnectionGetProxyInfo ENDP
th_WinHttpConnectionGetProxyList PROC
    jmp QWORD PTR [__imp_WinHttpConnectionGetProxyList]
th_WinHttpConnectionGetProxyList ENDP
th_WinHttpConnectionOnlyConvert PROC
    jmp QWORD PTR [__imp_WinHttpConnectionOnlyConvert]
th_WinHttpConnectionOnlyConvert ENDP
th_WinHttpConnectionOnlyReceive PROC
    jmp QWORD PTR [__imp_WinHttpConnectionOnlyReceive]
th_WinHttpConnectionOnlyReceive ENDP
th_WinHttpConnectionOnlySend PROC
    jmp QWORD PTR [__imp_WinHttpConnectionOnlySend]
th_WinHttpConnectionOnlySend ENDP
th_WinHttpConnectionSetPolicyEntries PROC
    jmp QWORD PTR [__imp_WinHttpConnectionSetPolicyEntries]
th_WinHttpConnectionSetPolicyEntries ENDP
th_WinHttpConnectionSetProxyInfo PROC
    jmp QWORD PTR [__imp_WinHttpConnectionSetProxyInfo]
th_WinHttpConnectionSetProxyInfo ENDP
th_WinHttpConnectionUpdateIfIndexTable PROC
    jmp QWORD PTR [__imp_WinHttpConnectionUpdateIfIndexTable]
th_WinHttpConnectionUpdateIfIndexTable ENDP
th_WinHttpCrackUrl PROC
    jmp QWORD PTR [__imp_WinHttpCrackUrl]
th_WinHttpCrackUrl ENDP
th_WinHttpCreateProxyList PROC
    jmp QWORD PTR [__imp_WinHttpCreateProxyList]
th_WinHttpCreateProxyList ENDP
th_WinHttpCreateProxyManager PROC
    jmp QWORD PTR [__imp_WinHttpCreateProxyManager]
th_WinHttpCreateProxyManager ENDP
th_WinHttpCreateProxyResolver PROC
    jmp QWORD PTR [__imp_WinHttpCreateProxyResolver]
th_WinHttpCreateProxyResolver ENDP
th_WinHttpCreateProxyResult PROC
    jmp QWORD PTR [__imp_WinHttpCreateProxyResult]
th_WinHttpCreateProxyResult ENDP
th_WinHttpCreateUiCompatibleProxyString PROC
    jmp QWORD PTR [__imp_WinHttpCreateUiCompatibleProxyString]
th_WinHttpCreateUiCompatibleProxyString ENDP
th_WinHttpCreateUrl PROC
    jmp QWORD PTR [__imp_WinHttpCreateUrl]
th_WinHttpCreateUrl ENDP
th_WinHttpDetectAutoProxyConfigUrl PROC
    jmp QWORD PTR [__imp_WinHttpDetectAutoProxyConfigUrl]
th_WinHttpDetectAutoProxyConfigUrl ENDP
th_WinHttpFreeProxyResult PROC
    jmp QWORD PTR [__imp_WinHttpFreeProxyResult]
th_WinHttpFreeProxyResult ENDP
th_WinHttpFreeProxyResultEx PROC
    jmp QWORD PTR [__imp_WinHttpFreeProxyResultEx]
th_WinHttpFreeProxyResultEx ENDP
th_WinHttpFreeProxySettings PROC
    jmp QWORD PTR [__imp_WinHttpFreeProxySettings]
th_WinHttpFreeProxySettings ENDP
th_WinHttpFreeProxySettingsEx PROC
    jmp QWORD PTR [__imp_WinHttpFreeProxySettingsEx]
th_WinHttpFreeProxySettingsEx ENDP
th_WinHttpFreeQueryConnectionGroupResult PROC
    jmp QWORD PTR [__imp_WinHttpFreeQueryConnectionGroupResult]
th_WinHttpFreeQueryConnectionGroupResult ENDP
th_WinHttpGetDefaultProxyConfiguration PROC
    jmp QWORD PTR [__imp_WinHttpGetDefaultProxyConfiguration]
th_WinHttpGetDefaultProxyConfiguration ENDP
th_WinHttpGetIEProxyConfigForCurrentUser PROC
    jmp QWORD PTR [__imp_WinHttpGetIEProxyConfigForCurrentUser]
th_WinHttpGetIEProxyConfigForCurrentUser ENDP
th_WinHttpGetProxyForUrl PROC
    jmp QWORD PTR [__imp_WinHttpGetProxyForUrl]
th_WinHttpGetProxyForUrl ENDP
th_WinHttpGetProxyForUrlEx PROC
    jmp QWORD PTR [__imp_WinHttpGetProxyForUrlEx]
th_WinHttpGetProxyForUrlEx ENDP
th_WinHttpGetProxyForUrlEx2 PROC
    jmp QWORD PTR [__imp_WinHttpGetProxyForUrlEx2]
th_WinHttpGetProxyForUrlEx2 ENDP
th_WinHttpGetProxyForUrlHvsi PROC
    jmp QWORD PTR [__imp_WinHttpGetProxyForUrlHvsi]
th_WinHttpGetProxyForUrlHvsi ENDP
th_WinHttpGetProxyResult PROC
    jmp QWORD PTR [__imp_WinHttpGetProxyResult]
th_WinHttpGetProxyResult ENDP
th_WinHttpGetProxyResultEx PROC
    jmp QWORD PTR [__imp_WinHttpGetProxyResultEx]
th_WinHttpGetProxyResultEx ENDP
th_WinHttpGetProxySettingsEx PROC
    jmp QWORD PTR [__imp_WinHttpGetProxySettingsEx]
th_WinHttpGetProxySettingsEx ENDP
th_WinHttpGetProxySettingsResultEx PROC
    jmp QWORD PTR [__imp_WinHttpGetProxySettingsResultEx]
th_WinHttpGetProxySettingsResultEx ENDP
th_WinHttpGetProxySettingsVersion PROC
    jmp QWORD PTR [__imp_WinHttpGetProxySettingsVersion]
th_WinHttpGetProxySettingsVersion ENDP
th_WinHttpGetTunnelSocket PROC
    jmp QWORD PTR [__imp_WinHttpGetTunnelSocket]
th_WinHttpGetTunnelSocket ENDP
th_WinHttpOpen PROC
    jmp QWORD PTR [__imp_WinHttpOpen]
th_WinHttpOpen ENDP
th_WinHttpOpenRequest PROC
    jmp QWORD PTR [__imp_WinHttpOpenRequest]
th_WinHttpOpenRequest ENDP
th_WinHttpPacJsWorkerMain PROC
    jmp QWORD PTR [__imp_WinHttpPacJsWorkerMain]
th_WinHttpPacJsWorkerMain ENDP
th_WinHttpProbeConnectivity PROC
    jmp QWORD PTR [__imp_WinHttpProbeConnectivity]
th_WinHttpProbeConnectivity ENDP
th_WinHttpProtocolCompleteUpgrade PROC
    jmp QWORD PTR [__imp_WinHttpProtocolCompleteUpgrade]
th_WinHttpProtocolCompleteUpgrade ENDP
th_WinHttpProtocolReceive PROC
    jmp QWORD PTR [__imp_WinHttpProtocolReceive]
th_WinHttpProtocolReceive ENDP
th_WinHttpProtocolSend PROC
    jmp QWORD PTR [__imp_WinHttpProtocolSend]
th_WinHttpProtocolSend ENDP
th_WinHttpQueryAuthSchemes PROC
    jmp QWORD PTR [__imp_WinHttpQueryAuthSchemes]
th_WinHttpQueryAuthSchemes ENDP
th_WinHttpQueryConnectionGroup PROC
    jmp QWORD PTR [__imp_WinHttpQueryConnectionGroup]
th_WinHttpQueryConnectionGroup ENDP
th_WinHttpQueryDataAvailable PROC
    jmp QWORD PTR [__imp_WinHttpQueryDataAvailable]
th_WinHttpQueryDataAvailable ENDP
th_WinHttpQueryHeaders PROC
    jmp QWORD PTR [__imp_WinHttpQueryHeaders]
th_WinHttpQueryHeaders ENDP
th_WinHttpQueryHeadersEx PROC
    jmp QWORD PTR [__imp_WinHttpQueryHeadersEx]
th_WinHttpQueryHeadersEx ENDP
th_WinHttpQueryOption PROC
    jmp QWORD PTR [__imp_WinHttpQueryOption]
th_WinHttpQueryOption ENDP
th_WinHttpReadData PROC
    jmp QWORD PTR [__imp_WinHttpReadData]
th_WinHttpReadData ENDP
th_WinHttpReadDataEx PROC
    jmp QWORD PTR [__imp_WinHttpReadDataEx]
th_WinHttpReadDataEx ENDP
th_WinHttpReadProxySettings PROC
    jmp QWORD PTR [__imp_WinHttpReadProxySettings]
th_WinHttpReadProxySettings ENDP
th_WinHttpReadProxySettingsHvsi PROC
    jmp QWORD PTR [__imp_WinHttpReadProxySettingsHvsi]
th_WinHttpReadProxySettingsHvsi ENDP
th_WinHttpReceiveResponse PROC
    jmp QWORD PTR [__imp_WinHttpReceiveResponse]
th_WinHttpReceiveResponse ENDP
th_WinHttpRefreshProxySettings PROC
    jmp QWORD PTR [__imp_WinHttpRefreshProxySettings]
th_WinHttpRefreshProxySettings ENDP
th_WinHttpRegisterProxyChangeNotification PROC
    jmp QWORD PTR [__imp_WinHttpRegisterProxyChangeNotification]
th_WinHttpRegisterProxyChangeNotification ENDP
th_WinHttpResetAutoProxy PROC
    jmp QWORD PTR [__imp_WinHttpResetAutoProxy]
th_WinHttpResetAutoProxy ENDP
th_WinHttpResolverGetProxyForUrl PROC
    jmp QWORD PTR [__imp_WinHttpResolverGetProxyForUrl]
th_WinHttpResolverGetProxyForUrl ENDP
th_WinHttpSaveProxyCredentials PROC
    jmp QWORD PTR [__imp_WinHttpSaveProxyCredentials]
th_WinHttpSaveProxyCredentials ENDP
th_WinHttpSendRequest PROC
    jmp QWORD PTR [__imp_WinHttpSendRequest]
th_WinHttpSendRequest ENDP
th_WinHttpSetCredentials PROC
    jmp QWORD PTR [__imp_WinHttpSetCredentials]
th_WinHttpSetCredentials ENDP
th_WinHttpSetDefaultProxyConfiguration PROC
    jmp QWORD PTR [__imp_WinHttpSetDefaultProxyConfiguration]
th_WinHttpSetDefaultProxyConfiguration ENDP
th_WinHttpSetOption PROC
    jmp QWORD PTR [__imp_WinHttpSetOption]
th_WinHttpSetOption ENDP
th_WinHttpSetProxySettingsPerUser PROC
    jmp QWORD PTR [__imp_WinHttpSetProxySettingsPerUser]
th_WinHttpSetProxySettingsPerUser ENDP
th_WinHttpSetSecureLegacyServersAppCompat PROC
    jmp QWORD PTR [__imp_WinHttpSetSecureLegacyServersAppCompat]
th_WinHttpSetSecureLegacyServersAppCompat ENDP
th_WinHttpSetStatusCallback PROC
    jmp QWORD PTR [__imp_WinHttpSetStatusCallback]
th_WinHttpSetStatusCallback ENDP
th_WinHttpSetTimeouts PROC
    jmp QWORD PTR [__imp_WinHttpSetTimeouts]
th_WinHttpSetTimeouts ENDP
th_WinHttpTimeFromSystemTime PROC
    jmp QWORD PTR [__imp_WinHttpTimeFromSystemTime]
th_WinHttpTimeFromSystemTime ENDP
th_WinHttpTimeToSystemTime PROC
    jmp QWORD PTR [__imp_WinHttpTimeToSystemTime]
th_WinHttpTimeToSystemTime ENDP
th_WinHttpUnregisterProxyChangeNotification PROC
    jmp QWORD PTR [__imp_WinHttpUnregisterProxyChangeNotification]
th_WinHttpUnregisterProxyChangeNotification ENDP
th_WinHttpWebSocketClose PROC
    jmp QWORD PTR [__imp_WinHttpWebSocketClose]
th_WinHttpWebSocketClose ENDP
th_WinHttpWebSocketCompleteUpgrade PROC
    jmp QWORD PTR [__imp_WinHttpWebSocketCompleteUpgrade]
th_WinHttpWebSocketCompleteUpgrade ENDP
th_WinHttpWebSocketQueryCloseStatus PROC
    jmp QWORD PTR [__imp_WinHttpWebSocketQueryCloseStatus]
th_WinHttpWebSocketQueryCloseStatus ENDP
th_WinHttpWebSocketReceive PROC
    jmp QWORD PTR [__imp_WinHttpWebSocketReceive]
th_WinHttpWebSocketReceive ENDP
th_WinHttpWebSocketSend PROC
    jmp QWORD PTR [__imp_WinHttpWebSocketSend]
th_WinHttpWebSocketSend ENDP
th_WinHttpWebSocketShutdown PROC
    jmp QWORD PTR [__imp_WinHttpWebSocketShutdown]
th_WinHttpWebSocketShutdown ENDP
th_WinHttpWriteData PROC
    jmp QWORD PTR [__imp_WinHttpWriteData]
th_WinHttpWriteData ENDP
th_WinHttpWriteProxySettings PROC
    jmp QWORD PTR [__imp_WinHttpWriteProxySettings]
th_WinHttpWriteProxySettings ENDP

END
